//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EarTrainer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EARTRAINER_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CONFIGURATION        129
#define IDD_DIALOG_INTERVAL             130
#define IDD_DIALOG_CHORD                131
#define IDD_DIALOG_PITCH                132
#define IDC_BUTTON_REPEAT_LAST_PLAYED   1000
#define IDC_BUTTON_PLAY_AND_SHOW_NOTES  1001
#define IDC_BUTTON_SHOWNOTESPLAYED      1002
#define IDC_BUTTON_PLAYNOTES            1003
#define IDC_EDIT_NOTES_PLAYED           1004
#define IDC_BUTTON_VALIDATE             1005
#define IDC_EDIT_RESULT                 1006
#define IDC_EDIT_INTERVAL               1007
#define IDC_RADIO_SIMPLE_MAJOR          1009
#define IDC_RADIO_INTERVAL_MAJOR        1010
#define IDC_RADIO_INTERVAL_CHROMATIC    1011
#define IDC_RADIO_ASCENDING             1012
#define IDC_RADIO_DESCENDING            1013
#define IDC_RADIO_ASC_DESC              1014
#define IDC_CHECK_FIXED_ROOT            1015
#define IDC_BUTTON_CONFIG_APPLY         1016
#define IDC_RADIO_MAJOR_MINOR           1017
#define IDC_RADIO_MAJOR_MINOR_SUS_AUG   1018
#define IDC_BUTTON_CHORD_PLAY           1019
#define IDC_RADIO_INPUT_MAJOR           1020
#define IDC_RADIO_INPUT_MINOR           1021
#define IDC_RADIO_INPUT_SUS4            1022
#define IDC_RADIO_INPUT_AUG             1023
#define IDC_EDIT_CHORD_PLAYED           1025
#define IDC_EDIT_CHORD_RESULT           1026
#define IDC_BUTTON_CHORD_VALIDATE       1027
#define IDC_BUTTON_CHORD_REPEAT_LAST_PLAYED 1028
#define IDC_BUTTON_CHORD_SHOW_CHORD_PLAYED 1029
#define IDC_BUTTON_CHORD_PLAY_AND_SHOW  1030
#define IDC_CHECK_CHORD_FIXED_ROOT      1031
#define IDC_RADIO_CHORD_INVERSION_NONE  1032
#define IDC_RADIO_CHORD_INVERSION_ALLOWED 1033
#define IDC_BUTTON_CHORD_PLAY_CORRESPONDING_MAJOR_MINOR 1034
#define IDC_COMBO_PITCH_LIST            1037
#define IDC_BUTTON_PITCH_PLAY           1038
#define IDC_BUTTON_PITCH_PLAY_NOTE_SEQUENCE 1039
#define IDC_BUTTON_PITCH_STOP_NOTE_SEQUENCE 1040
#define IDC_BUTTON_PITCH_PRESS_IF_MATCHED 1041
#define IDC_EDIT_PITCH_RESULT           1042
#define IDC_EDIT_PITCH_NOTES_PLAYED     1043
#define IDC_BUTTON_PITCH_SHOW_NOTES_PLAYED 1044
#define IDC_SPIN_PITCH_TEMPO            1045
#define IDC_EDIT_PITCH_TEMPO            1046
#define IDC_BUTTON_INTERVAL_CLEAR_RESULTS 1047
#define IDC_COMBO_CONFIG_VOICES         1049
#define IDC_COMBO_CONFIG_CHANNEL        1050
#define IDC_BUTTON_CONFIG_PLAY          1051
#define IDC_BUTTON_CONFIG_STOP          1052
#define IDC_BUTTON_PITCH_STOP           1053
#define IDC_BUTTON_CHORD_STOP           1054
#define IDC_COMBO_CONFIG_DEVICE         1055
#define IDC_EDIT_INTERVAL_TEMPO         1057
#define IDC_SPIN_INTERVAL_TEMPO         1058
#define IDC_SLIDER_PITCH_PROBABILITY    1059
#define IDC_SLIDER_CONFIG_VELOCITY      1060
#define IDC_COMBO_PITCH_MIN             1061
#define IDC_COMBO_PITCH_MAX             1062
#define IDC_CHECK_INTERVAL_ASC_1        1064
#define IDC_CHECK_INTERVAL_ASC_2        1066
#define IDC_CHECK_INTERVAL_ASC_3        1067
#define IDC_CHECK_INTERVAL_ASC_4        1068
#define IDC_CHECK_INTERVAL_ASC_5        1069
#define IDC_CHECK_INTERVAL_ASC_6        1070
#define IDC_CHECK_INTERVAL_ASC_7        1071
#define IDC_CHECK_INTERVAL_ASC_8        1072
#define IDC_CHECK_INTERVAL_ASC_9        1073
#define IDC_CHECK_INTERVAL_ASC_10       1074
#define IDC_CHECK_INTERVAL_ASC_11       1075
#define IDC_CHECK_INTERVAL_ASC_12       1076
#define IDC_CHECK_INTERVAL_DESC_12      1077
#define IDC_CHECK_INTERVAL_DESC_11      1078
#define IDC_CHECK_INTERVAL_DESC_10      1079
#define IDC_CHECK_INTERVAL_DESC_9       1080
#define IDC_CHECK_INTERVAL_DESC_8       1081
#define IDC_CHECK_INTERVAL_DESC_7       1082
#define IDC_CHECK_INTERVAL_DESC_6       1083
#define IDC_CHECK_INTERVAL_DESC_5       1084
#define IDC_CHECK_INTERVAL_DESC_4       1085
#define IDC_CHECK_INTERVAL_DESC_3       1086
#define IDC_CHECK_INTERVAL_DESC_2       1087
#define IDC_CHECK_INTERVAL_DESC_1       1088
#define IDC_COMBO_INTERVAL_PITCH        1090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
